# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6da56590f6fb51e3c859c0e6b6db72a41f340c04a20d8064b7c4236d2cac0063d56a605e1d4ba52c116f716fb0bc13151422f09870979034c7d19a35b0bd8c5d

test:
  secret_key_base: ba95b3097b1954e50d04f4dfb2067e87c5786e94aefea25b331faa53af19e56bf6e57733f228aa19fb99774e526dde3d22edbe8c66a020376bd907a31cad77d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
